import { useCallback } from "react";
import { useNavigate } from "react-router-dom";

export function normalizeNavLabel(raw: string): string {
  return raw
    .replace(/\s+(opened|selected)$/i, "")
    .replace(/^[\d]+[.)]\s+/u, "")
    .replace(/[?]/g, "")
    .replace(/\s*&\s*/g, " ")
    .replace(/^[^A-Za-z0-9]+/u, "")
    .replace(/\s*[›▾⌄⌃●·]+$/u, "")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}

const NAV_ROUTES: Record<string, string> = {
  home: "/",
  "ai observatory": "/",
  overview: "/",
  documentation: "/documentation",
  docs: "/documentation",
  help: "/documentation",
  "help docs": "/documentation",
  guide: "/documentation",
  guides: "/documentation",
  "cheat sheet": "/documentation",
  "cheat sheets": "/documentation",
  cheatsheets: "/documentation",
  glossary: "/documentation",
  papers: "/documentation",
  resources: "/documentation",
  "help resources": "/documentation",
  teacher: "/documentation",
  support: "/documentation",
  tutorials: "/documentation",
  "key formulas": "/documentation",
  "further reading": "/documentation",
  reading: "/documentation",
  hints: "/documentation",
  code: "/documentation",
  api: "/documentation",
  prerequisites: "/documentation",
  curriculum: "/sitemap",
  sitemap: "/sitemap",
  roadmap: "/sitemap",
  roadmaps: "/sitemap",
  "lesson roadmap": "/sitemap",
  courses: "/sitemap",
  lessons: "/sitemap",
  "all lessons": "/sitemap",
  "learning paths": "/sitemap",
  pathways: "/sitemap",
  explore: "/sitemap",
  learn: "/sitemap",
  bookmarks: "/sitemap",
  "what's new": "/sitemap",
  algorithms: "/sitemap",
  "implementation matrix": "/implementation-matrix",
  achievements: "/implementation-matrix",
  matrix: "/implementation-matrix",
  benchmarks: "/implementation-matrix",
  notes: "/ml/lab/experiment-workspace",
  notebooks: "/ml/lab/experiment-workspace",
  notebook: "/ml/lab/experiment-workspace",
  workspaces: "/ml/lab/experiment-workspace",
  workbench: "/ml/lab/experiment-workspace",
  "my workspace": "/ml/lab/experiment-workspace",
  projects: "/ml/lab/experiment-workspace",
  "new project": "/ml/lab/experiment-workspace",
  "new session": "/ml/lab/experiment-workspace",
  "open session": "/ml/lab/experiment-workspace",
  "save session": "/ml/lab/experiment-workspace",
  experiments: "/ml/lab/saved-experiments",
  "saved experiments": "/ml/lab/saved-experiments",
  visualizations: "/ml/lab/training-visualizations",
  playground: "/ml/deep-learning/nn-playground",
  playgrounds: "/ml/deep-learning/nn-playground",
  practice: "/ml/lab/algorithm-comparison",
  "more tools": "/ml/lab/algorithm-comparison",
  datasets: "/ml/lab/dataset-manager",
  dataset: "/ml/lab/dataset-manager",
  "dataset library": "/dataset-library",
  "sample datasets": "/dataset-library",
  "dataset manager": "/ml/lab/dataset-manager",
  "data lab": "/ml/lab/dataset-manager",
  data: "/ml/lab/dataset-manager",
  upload: "/ml/lab/dataset-manager",
  uploads: "/ml/lab/dataset-manager",
  "data hub": "/ml/lab/dataset-intelligence",
  "data registry": "/dataset-library",
  "data sources": "/dataset-library",
  "my collections": "/dataset-library",
  favorites: "/dataset-library",
  "feature store": "/ml/lab/dataset-intelligence",
  insights: "/ml/lab/dataset-intelligence",
  models: "/ml/lab/model-zoo",
  "model registry": "/ml/lab/model-zoo",
  registry: "/ml/lab/model-zoo",
  automl: "/ml/lab/automl-assistant",
  "tune hyperparameters": "/ml/lab/tuning-engine",
  "compare models": "/ml/lab/model-comparison",
  pipelines: "/ml/lab/architecture-flow",
  architecture: "/ml/lab/architecture-flow",
  deployments: "/ml/deployment/export-hub",
  deploy: "/ml/deployment/export-hub",
  reports: "/ml/lab/report-builder",
  train: "/ml/lab/train-your-model",
  evaluate: "/ml/evaluation/train-test-split",
  evaluations: "/ml/evaluation/train-test-split",
  "model evaluation": "/ml/evaluation/train-test-split",
  monitoring: "/ml/lab/performance-dashboard",
  monitor: "/ml/lab/performance-dashboard",
  "model monitor": "/ml/lab/performance-dashboard",
  "drift monitor": "/ml/lab/performance-dashboard",
  drift: "/ml/lab/performance-dashboard",
  alerts: "/ml/lab/performance-dashboard",
  observability: "/ml/lab/performance-dashboard",
  mlops: "/ml/deployment/export-hub",
  "supervised learning": "/ml/supervised/simple-linear-regression",
  "unsupervised learning": "/ml/clustering/k-means",
  "deep learning": "/ml/deep-learning/perceptron",
  "dimensionality reduction": "/ml/dimensionality-reduction/pca",
  "time series": "/ml/time-series/moving-average",
  forecasting: "/ml/time-series/arima-concept",
  "anomaly detection": "/ml/time-series/anomaly-detection",
  classification: "/ml/supervised/logistic-regression",
  regression: "/ml/supervised/simple-linear-regression",
  clustering: "/ml/clustering/k-means",
  "what is clustering": "/ml/clustering/k-means",
  "k-means": "/ml/clustering/k-means",
  "k-means clustering": "/ml/clustering/k-means",
  "dbscan lab": "/ml/clustering/dbscan",
  dbscan: "/ml/clustering/dbscan",
  hierarchical: "/ml/clustering/hierarchical-clustering",
  "hierarchical clustering": "/ml/clustering/hierarchical-clustering",
  "mean shift": "/ml/clustering/mean-shift",
  "gaussian mixture": "/ml/clustering/gaussian-mixture-model",
  "gaussian mixture model": "/ml/clustering/gaussian-mixture-model",
  "spectral clustering": "/ml/clustering/spectral-clustering",
  optics: "/ml/clustering/optics",
  birch: "/ml/clustering/hierarchical-clustering",
  "feature engineering": "/ml/preprocessing/polynomial-features",
  "feature interactions": "/ml/preprocessing/polynomial-features",
  "polynomial features": "/ml/preprocessing/polynomial-features",
  "feature scaling": "/ml/preprocessing/scaling-normalization",
  "scaling normalization": "/ml/preprocessing/scaling-normalization",
  scaling: "/ml/preprocessing/scaling-normalization",
  encoding: "/ml/preprocessing/categorical-encoding",
  "encoding categorical": "/ml/preprocessing/categorical-encoding",
  "missing values": "/ml/preprocessing/missing-values",
  outliers: "/ml/preprocessing/outlier-detection",
  "outlier detection": "/ml/preprocessing/outlier-detection",
  "feature selection": "/ml/preprocessing/feature-selection",
  preprocessing: "/ml/preprocessing/missing-values",
  "linear regression": "/ml/supervised/simple-linear-regression",
  "ridge regression": "/ml/supervised/ridge-regression",
  "logistic regression": "/ml/supervised/logistic-regression",
  "gradient boosting": "/ml/supervised/gradient-boosting-classification",
  "svm classification": "/ml/supervised/svm-classification",
  "lstm networks": "/ml/deep-learning/lstm",
  "lstm traffic": "/ml/time-series/lstm-forecasting",
  "lstm forecasting": "/ml/time-series/lstm-forecasting",
  "rnn forecasting": "/ml/time-series/rnn-forecasting",
  "gru forecasting": "/ml/time-series/gru-forecasting",
  "arima lab": "/ml/time-series/arima-concept",
  "demand forecasting": "/ml/time-series/holt-winters",
  "n-beats load": "/ml/time-series/rnn-forecasting",
  "prophet energy": "/ml/time-series/arima-concept",
  "tcn anomaly": "/ml/time-series/anomaly-detection",
  "reinforcement learning": "/ml/reinforcement-learning/q-learning-grid-world",
  "core concepts": "/ml/evaluation/bias-variance-tradeoff",
  "regression metrics": "/ml/evaluation/regression-metrics",
  discussions: "/documentation",
  mentors: "/documentation",
  events: "/documentation",
  settings: "/documentation",
  profile: "/documentation",
  team: "/documentation",
  billing: "/documentation",
  "data scientist track": "/ml/lab/algorithm-comparison",
  "beginner path": "/ml/supervised/simple-linear-regression",
  "intermediate path": "/ml/supervised/ridge-regression",
  "advanced path": "/ml/deep-learning/transformer-attention",
  "customer churn": "/dataset-library",
  "fraud detection": "/dataset-library",
  "market basket": "/dataset-library",
  "medical imaging": "/dataset-library",
  "text analytics": "/dataset-library",
  "customer churn dataset": "/dataset-library",
  "heart disease dataset": "/dataset-library",
  "titanic survival dataset": "/dataset-library",
  "house prices dataset": "/dataset-library",
  "iris dataset": "/dataset-library",
};

export function resolveNavRoute(label: string): string | undefined {
  return NAV_ROUTES[normalizeNavLabel(label)];
}

export function useLabNavigate() {
  const navigate = useNavigate();
  return useCallback(
    (label: string) => {
      const route = resolveNavRoute(label);
      if (!route) return false;
      navigate(route);
      return true;
    },
    [navigate],
  );
}
