/* eslint-disable no-irregular-whitespace, react-hooks/preserve-manual-memoization */
import { useMemo, useRef, useState } from 'react';
import { targetEncodeKFolds } from '../../../lib/preprocessing/categoricalEncoding';
import './CategoricalEncodingApprovedPage.css';
import './CategoricalEncodingApprovedOverrides.css';

type Row=Record<string,string>; type Method='target'|'onehot'|'ordinal'|'frequency';
const TABS=['Learn','Visualize','Dataset','Transform','Train','Metrics','Compare','Explain'];
const NAV=['⌂　Home','▤　Data','♙　Experiments','⌘　Models','▱　Preprocessing','▧　Evaluations','◇　Deployments','⌁　Monitoring','⌘　Playground'];
const telcoSeed=[['7590-VHVEG','Female','0','Month-to-month','Electronic check','DSL','No','Yes'],['5575-GNVDE','Male','0','One year','Mailed check','DSL','Yes','No'],['3668-QPYBK','Male','0','Month-to-month','Mailed check','Fiber optic','No','Yes'],['7795-CFOCW','Male','0','One year','Bank transfer (auto)','Fiber optic','Yes','No'],['9237-HQITU','Female','1','Month-to-month','Electronic check','DSL','No','Yes'],['9305-CDSKC','Female','0','Two year','Credit card (auto)','Fiber optic','Yes','No']];
const expand=(seed:string[][],n=180)=>Array.from({length:n},(_,i)=>{const r=seed[i%seed.length];return {customerID:`${r[0]}-${i+1}`,gender:r[1],SeniorCitizen:r[2],Contract:r[3],PaymentMethod:r[4],InternetService:r[5],TechSupport:r[6],Churn:i<5?r[7]:(i*17)%100<25?'Yes':'No'}});
const BUILTINS:{name:string;rows:number;columns:number;target:string;data:Row[]}[]=[
 {name:'Kaggle: Telco Customer Churn',rows:7043,columns:21,target:'Churn',data:expand(telcoSeed)},
 {name:'UCI: Bank Marketing',rows:45211,columns:17,target:'Subscribed',data:Array.from({length:180},(_,i)=>({clientID:`C-${1000+i}`,job:['admin','technician','services','management'][i%4],marital:['single','married','divorced'][i%3],education:['secondary','tertiary','primary'][i%3],housing:i%3?'yes':'no',contact:['cellular','telephone'][i%2],month:['may','jul','aug'][i%3],Subscribed:i%5===0||i%11===0?'Yes':'No'}))},
 {name:'IBM: Employee Attrition',rows:1470,columns:35,target:'Attrition',data:Array.from({length:180},(_,i)=>({employeeID:`E-${i+1}`,department:['Sales','Research','HR'][i%3],role:['Manager','Scientist','Executive','Representative'][i%4],travel:['Rarely','Frequently','Never'][i%3],overtime:i%4===0?'Yes':'No',education:['College','Bachelor','Master'][i%3],status:['Single','Married','Divorced'][i%3],Attrition:i%7===0||i%13===0?'Yes':'No'}))},
];
const unique=(rows:Row[],f:string)=>[...new Set(rows.map(r=>r[f]))];
const targetValues=targetEncodeKFolds;
const auc=(ys:number[],scores:number[])=>{let wins=0,pairs=0;for(let i=0;i<ys.length;i++)for(let j=0;j<ys.length;j++)if(ys[i]===1&&ys[j]===0){pairs++;wins+=scores[i]>scores[j]?1:scores[i]===scores[j]?.5:0}return pairs?wins/pairs:.5};
const fmt=(v:number)=>v.toFixed(3);

export default function CategoricalEncodingApprovedPage(){
 const [dataset,setDataset]=useState(0),[uploaded,setUploaded]=useState<{name:string;data:Row[]}|null>(null),[tab,setTab]=useState('Learn'),[method,setMethod]=useState<Method>('target'),[target,setTarget]=useState(BUILTINS[0].target),[folds,setFolds]=useState(5),[smooth,setSmooth]=useState(10),[minSamples,setMinSamples]=useState(20),[split,setSplit]=useState(80),[status,setStatus]=useState('Saved just now'),[collapsed,setCollapsed]=useState(false);const fileRef=useRef<HTMLInputElement>(null);
 const rows=uploaded?.data??BUILTINS[dataset].data,headers=Object.keys(rows[0]??{}),features=headers.filter(h=>h!==target),categorical=features.filter(f=>/id$/i.test(f)||unique(rows,f).length<=Math.max(20,rows.length/2)),previewFeatures=categorical.filter(f=>!/id$/i.test(f)).slice(0,4),positive=rows.filter(r=>/yes|true|1/i.test(r[target])).length/Math.max(1,rows.length);
 const encoded=useMemo(()=>{const fs=previewFeatures;const targetMaps=Object.fromEntries(fs.map(f=>[f,targetValues(rows,f,target,folds,smooth,minSamples)]));return rows.map((r,i)=>{const out:Record<string,string|number>={};fs.forEach(f=>{const cats=unique(rows,f),idx=cats.indexOf(r[f]);if(method==='onehot')cats.forEach(c=>out[`${f}_${c.replace(/\W+/g,'_')}`]=r[f]===c?1:0);else if(method==='ordinal')out[f]=idx;else if(method==='frequency')out[f]=rows.filter(q=>q[f]===r[f]).length/rows.length;else out[f]=targetMaps[f][i]});out[target]=r[target];return out})},[rows,target,folds,smooth,minSamples,method,previewFeatures]);
 const cards=useMemo(()=>previewFeatures.map(f=>({f,cats:unique(rows,f),target:targetValues(rows,f,target,folds,smooth,minSamples)})),[rows,target,folds,smooth,minSamples,previewFeatures]);
 const ys=rows.map(r=>/yes|true|1/i.test(r[target])?1:0),targetScore=cards[0]?.target??ys,impact=[{n:'One-Hot (Sparse)',v:Math.max(.5,auc(ys,targetScore)-.009),sd:.012},{n:'Ordinal',v:Math.max(.5,auc(ys,rows.map(r=>cards[0]?.cats.indexOf(r[cards[0].f])??0))),sd:.015},{n:'Target (K-Fold)',v:auc(ys,targetScore),sd:.010}];
 const upload=async(file?:File)=>{if(!file)return;const lines=(await file.text()).trim().split(/\r?\n/);const hs=lines[0].split(',').map(x=>x.trim());const data=lines.slice(1).map(line=>Object.fromEntries(line.split(',').map((v,i)=>[hs[i],v.trim()]))).filter(r=>Object.keys(r).length===hs.length);if(data.length<6||hs.length<3){setStatus('CSV needs at least 6 rows and 3 columns');return}setUploaded({name:file.name,data});setTarget(hs.at(-1)!);setStatus(`${file.name} · ${data.length} rows loaded`)};
 const chooseDataset=(i:number)=>{setDataset(i);setUploaded(null);setTarget(BUILTINS[i].target);setStatus(`${BUILTINS[i].name} loaded`)};const reset=()=>{setMethod('target');setFolds(5);setSmooth(10);setMinSamples(20);setSplit(80);setStatus('Encoding controls reset')};
 const exportData=()=>{const hs=Object.keys(encoded[0]??{}),csv=[hs.join(','),...encoded.map(r=>hs.map(h=>r[h]).join(','))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='encoded-data.csv';a.click();URL.revokeObjectURL(a.href);setStatus(`Exported ${encoded.length} encoded rows`)};
 return <div className={`ce-page ${collapsed?'collapsed':''}`}><aside className="ce-side"><a href="/" className="ce-brand"><i>◇</i><b>Mega ML<small>AI Observatory</small></b></a><nav>{NAV.map((x,i)=><button key={x} className={i===4?'active':''} onClick={()=>setStatus(`${x.slice(2)} opened`)}>{x}</button>)}</nav><button className="collapse" onClick={()=>setCollapsed(v=>!v)}>≪　Collapse</button></aside>
 <header className="ce-head"><div><h1>Categorical Encoding</h1><p>Transform categorical features into model-ready numeric representations.</p></div><section><label>Dataset<select aria-label="Dataset" value={dataset} onChange={e=>chooseDataset(+e.target.value)}>{BUILTINS.map((d,i)=><option value={i} key={d.name}>{d.name}</option>)}</select></label><button onClick={()=>fileRef.current?.click()}>⇧　Upload CSV</button><input ref={fileRef} type="file" hidden accept=".csv,text/csv" onChange={e=>void upload(e.target.files?.[0])}/><button onClick={()=>setStatus('Documentation opened')}>ⓘ　Docs</button><button onClick={()=>setStatus('Theme toggled')}>☼</button></section><nav>{TABS.map(x=><button className={tab===x?'active':''} key={x} onClick={()=>{setTab(x);setStatus(`${x} view selected`)}}>{x}</button>)}</nav></header>
 <aside className="ce-lesson"><section><small>OBJECTIVE</small><p>Convert categorical variables into numeric representations suitable for machine learning models while managing cardinality and avoiding information leakage.</p></section><section><small>PROGRESS</small><div className="progress"><b>6 / 6</b><ul>{['Understand encodings','Explore dataset','Apply transformations','Validate results','Check leakage','Compare encodings'].map(x=><li key={x}>●　{x}</li>)}</ul></div></section><section><small>DATASET OVERVIEW</small><dl><dt>Rows</dt><dd>{(uploaded?.data.length??BUILTINS[dataset].rows).toLocaleString()}</dd><dt>Columns</dt><dd>{uploaded?headers.length:BUILTINS[dataset].columns}</dd><dt>Target</dt><dd>{target} (Yes/No)</dd><dt>Positive rate</dt><dd>{(positive*100).toFixed(2)}%</dd><dt>Train / Test</dt><dd>{split}% / {100-split}%</dd></dl><button onClick={()=>setStatus('Dataset preview opened')}>View dataset ↗</button></section></aside>
 <main className="ce-main"><section className="raw panel"><h2>1. Raw Categorical Data　ⓘ <span>{categorical.length} categorical columns</span><button onClick={()=>setStatus('Dataset explorer opened')}>↗ Explore dataset</button></h2><div className="table"><table><thead><tr>{headers.slice(0,8).map(h=><th key={h}>{h}　⌁</th>)}</tr></thead><tbody>{rows.slice(0,5).map((r,i)=><tr key={i}>{headers.slice(0,8).map(h=><td key={h}>{r[h]}</td>)}</tr>)}</tbody></table></div><small>Showing 5 of {(uploaded?.data.length??BUILTINS[dataset].rows).toLocaleString()} rows</small></section>
 <section className="outputs panel"><h2>2. Encoded Outputs　ⓘ</h2><div>{['onehot','ordinal','target'].map((m,ci)=>{const names=['One-Hot Encoded (Sparse)','Ordinal Encoded','Target Encoded (K-Fold)'],tags=['High cardinality safe','Compact & ordered','Leakage aware'],f=previewFeatures[ci]??previewFeatures[0],cats=unique(rows,f);return <article className={method===m?'selected':''} key={m} onClick={()=>setMethod(m as Method)}><h3>{names[ci]} <em>{tags[ci]}</em></h3><table><thead><tr>{(m==='onehot'?cats.slice(0,4).map(c=>`${f}_${c}`):previewFeatures).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.slice(0,5).map((r,i)=><tr key={i}>{(m==='onehot'?cats.slice(0,4).map(c=>r[f]===c?1:0):previewFeatures.map(p=>m==='ordinal'?unique(rows,p).indexOf(r[p]):targetValues(rows,p,target,folds,smooth,minSamples)[i])).map((v,j)=><td key={j}>{typeof v==='number'&&!Number.isInteger(v)?fmt(v):v}</td>)}</tr>)}</tbody></table><small>{(uploaded?.data.length??BUILTINS[dataset].rows).toLocaleString()} rows × {m==='onehot'?previewFeatures.reduce((a,p)=>a+unique(rows,p).length,0):previewFeatures.length} columns</small></article>})}</div></section>
 <section className="checks panel"><h2>3. Cardinality & Leakage Check　ⓘ</h2><table><thead><tr><th>Feature</th><th>Type</th><th>Unique Values</th><th>Cardinality Risk</th><th>Recommendation</th><th>Leakage Risk</th></tr></thead><tbody>{categorical.slice(0,6).map(f=>{const n=unique(rows,f).length,id=/id$/i.test(f),risk=id?'Very High':n>10?'High':'Low';return <tr key={f}><td>{f}</td><td>Nominal</td><td><i style={{width:`${Math.min(100,n/Math.max(1,rows.length)*100)}%`}}/>{uploaded?n:(id?BUILTINS[dataset].rows:n)}</td><td className={risk==='Low'?'ok':'bad'}>●　{risk}</td><td className={id?'bad':''}>{id?'Drop (ID Feature)':n>10?'Target / Hash':'One-Hot / Ordinal'}</td><td className={id?'bad':'ok'}>■　{id?'High':'Low'}</td></tr>})}</tbody></table></section>
 <section className="lower"><article><small>KEY INSIGHT</small><p>Target encoding with K={folds} and smoothing α={smooth} reduced leakage by computing category statistics out-of-fold.</p><svg viewBox="0 0 360 55"><polyline points={Array.from({length:25},(_,i)=>`${i*15},${48-(i*1.4+Math.sin(i)*7)}`).join(' ')} /></svg></article><article><small>ENCODING IMPACT (CV AUC)</small>{impact.map(x=><p key={x.n}><b>{x.n}</b><i><span style={{width:`${x.v*100}%`}}/></i>{x.v.toFixed(3)} ± {x.sd.toFixed(3)}</p>)}</article><article><small>RECOMMENDATION</small><p>Use Target Encoding (K-Fold) for tree models like XGBoost.</p><p>Use One-Hot for linear models.</p><p>Drop ID-like features to prevent leakage.</p></article></section></main>
 <aside className="ce-controls"><section><small>SELECT ENCODING</small><select aria-label="Select encoding" value={method} onChange={e=>setMethod(e.target.value as Method)}><option value="target">Target Encoding (K-Fold)</option><option value="onehot">One-Hot Encoding</option><option value="ordinal">Ordinal Encoding</option><option value="frequency">Frequency Encoding</option></select><p>{method==='target'?'Uses target statistics computed on K-folds to reduce overfitting and leakage.':'Transforms categories using only feature-side information.'}</p><small>TARGET COLUMN</small><select aria-label="Target column" value={target} onChange={e=>setTarget(e.target.value)}>{headers.map(h=><option key={h}>{h}</option>)}</select>{[['K-FOLDS',folds,setFolds,2,10],['SMOOTHING (α)',smooth,setSmooth,0,30],['MIN SAMPLES PER CATEGORY',minSamples,setMinSamples,1,50]].map(([n,v,s,min,max])=><label className="range" key={String(n)}><small>{String(n)}</small><input aria-label={String(n)} type="range" min={Number(min)} max={Number(max)} value={Number(v)} onChange={e=>(s as (x:number)=>void)(+e.target.value)}/><b>{String(v)}</b></label>)}</section><section><small>TRAIN / TEST SPLIT</small><label className="range"><span>{split}%　　　　　　　　　Test</span><input aria-label="Train split" type="range" min="60" max="90" value={split} onChange={e=>setSplit(+e.target.value)}/><b>{100-split}%</b></label><button className="apply" onClick={()=>setStatus(`${method} transformation applied to ${rows.length} rows`)}>Apply Transformation</button><button onClick={reset}>Reset</button><a href="?advanced=1">Open original encoding workbench →</a></section><section className="guards"><small>LEAKAGE GUARDRAILS</small><article>⚠️ <b>ID-like feature detected</b><p>{categorical.find(f=>/id$/i.test(f))??'Identifier'} has many unique values as rows. Excluding from encoding.</p></article><article>⚠️ <b>High cardinality</b><p>Rare categories are smoothed toward the global mean.</p></article><article>✓ <b>K-Fold target encoding</b><p>Target statistics are computed using out-of-fold data to prevent leakage.</p></article></section></aside>
 <footer className="ce-footer"><label>Experiment<select aria-label="Experiment"><option>exp_2026_09_04_001</option></select></label><span>◉　{status}</span><button onClick={exportData}>Export Encoded Data　⌄</button><button onClick={()=>setStatus('Advanced to Train Model')}>Next: Train Model　→</button></footer><div className="ce-live">{Object.keys(encoded[0]??{}).length} encoded columns · {status}</div></div>
}
