/* eslint-disable no-irregular-whitespace, react-hooks/preserve-manual-memoization */
import { useMemo, useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useLabNavigate } from '../../../lib/labNavigation';
import { mean, quantile, std } from '../../../lib/math/statistics';
import { capAtIqrFences, detectOutliers, type OutlierMethod, type OutlierResult } from '../../../lib/preprocessing/outlierDetection';
import './OutlierDetectionApprovedPage.css';

type Row=Record<string,number>; const TABS=['Learn','Visualize','Dataset','Transform','Metrics','Compare','Live Test / Inference'];
const FEATURES=['PM2.5 (µg/m³)','PM10 (µg/m³)','NO2 (ppb)','O3 (ppb)','CO (ppm)','SO2 (ppb)','AQI'];
function seeded(seed:number){let s=seed>>>0;return()=>((s=(s*1664525+1013904223)>>>0)/4294967296)}
function makeRows(seed:number,n=520){const r=seeded(seed);return Array.from({length:n},(_,i)=>{const spike=i%47===0?80+r()*90:i%29===0?35+r()*40:0,pm25=Math.max(2,8+Math.pow(r(),2.2)*48+spike),pm10=pm25*(1.45+r()*.55)+r()*15;return {'PM2.5 (µg/m³)':pm25,'PM10 (µg/m³)':pm10,'NO2 (ppb)':12+r()*45+spike*.16,'O3 (ppb)':18+r()*42-spike*.04,'CO (ppm)':.2+r()*1.1+spike*.005,'SO2 (ppb)':2+r()*18+spike*.08,AQI:Math.min(300,pm25*1.3+pm10*.35)}})}
const DATASETS=[{name:'Synthetic air quality · sample A',data:makeRows(74)},{name:'Synthetic air quality · sample B',data:makeRows(88,640)},{name:'Synthetic air quality · sample C',data:makeRows(103,480)}];
function correlation(xs:number[],ys:number[]){const mx=mean(xs),my=mean(ys),num=xs.reduce((sum,x,i)=>sum+(x-mx)*(ys[i]-my),0),dx=Math.sqrt(xs.reduce((sum,x)=>sum+(x-mx)**2,0)),dy=Math.sqrt(ys.reduce((sum,y)=>sum+(y-my)**2,0));return dx&&dy?num/dx/dy:0}

export default function OutlierDetectionApprovedPage(){
 const [dataset,setDataset]=useState(0),[uploaded,setUploaded]=useState<{name:string;rows:Row[]}|null>(null),[method,setMethod]=useState<OutlierMethod>('iqr'),[feature,setFeature]=useState(FEATURES[0]),[multiplier,setMultiplier]=useState(1.5),[inspect,setInspect]=useState(false),[probe,setProbe]=useState(50),[status,setStatus]=useState('Ready to explore'),[collapsed,setCollapsed]=useState(false),[modified,setModified]=useState<Row[]|null>(null);const fileRef=useRef<HTMLInputElement>(null);const go=useLabNavigate();const [params,setParams]=useSearchParams();const tab=TABS.find(x=>x.toLowerCase()===params.get('tab')?.toLowerCase()||(x==='Live Test / Inference'&&params.get('tab')==='inference'))??'Visualize';const setTab=(next:string)=>setParams(previous=>{const copy=new URLSearchParams(previous);copy.set('tab',next==='Live Test / Inference'?'inference':next.toLowerCase());return copy});
 const rows=modified??uploaded?.rows??DATASETS[dataset].data,features=Object.keys(rows[0]??{}),activeFeature=features.includes(feature)?feature:features[0],values=rows.map(r=>r[activeFeature]),results=useMemo(()=>detectOutliers(values,method,multiplier),[values,method,multiplier]),counts={normal:results.filter(x=>x.band==='normal').length,mild:results.filter(x=>x.band==='mild').length,severe:results.filter(x=>x.band==='severe').length};
 const q1=quantile(values,.25),q3=quantile(values,.75),med=quantile(values,.5),iqr=q3-q1,center=mean(values),spread=std(values),lower=method==='iqr'?q1-multiplier*iqr:center-multiplier*spread,upper=method==='iqr'?q3+multiplier*iqr:center+multiplier*spread,max=Math.max(...values),min=Math.min(...values),partner=features.find(f=>f!==activeFeature)??activeFeature,pvals=rows.map(r=>r[partner]);
 const histBands=Array.from({length:32},()=>({normal:0,mild:0,severe:0}));values.forEach((v,i)=>{const bin=Math.min(31,Math.floor((v-min)/(max-min||1)*32));histBands[bin][results[i].band]++});const histPeak=Math.max(1,...histBands.map(bin=>bin.normal+bin.mild+bin.severe));const chartX=(v:number)=>45+(v-min)/(max-min||1)*335; const upload=async(file?:File)=>{if(!file)return;const lines=(await file.text()).trim().split(/\r?\n/),hs=lines[0].split(',').map(x=>x.trim()),parsed=lines.slice(1).map(line=>line.split(',').map(Number)).filter(v=>v.length===hs.length&&v.every(Number.isFinite)).map(v=>Object.fromEntries(hs.map((h,i)=>[h,v[i]])));if(parsed.length<8){setStatus('CSV needs at least 8 complete numeric rows');return}setUploaded({name:file.name,rows:parsed});setModified(null);setFeature(hs[0]);setStatus(`${file.name} · ${parsed.length} rows loaded`)};
 const chooseDataset=(i:number)=>{setDataset(i);setUploaded(null);setModified(null);setFeature(FEATURES[0]);setStatus(`${DATASETS[i].name} loaded`)};const reset=()=>{setMethod('iqr');setFeature(FEATURES[0]);setMultiplier(1.5);setInspect(false);setModified(null);setStatus('Outlier view reset')};
 const remove=()=>{const kept=rows.filter((_,i)=>results[i].band==='normal');if(!kept.length){setStatus('No normal rows remain; increase the threshold');return}setModified(kept);setStatus(`Removed ${counts.mild+counts.severe} flagged observations`)};const cap=()=>{const capped=method==='iqr'?capAtIqrFences(values,multiplier):values.map(value=>Math.max(lower,Math.min(upper,value)));const changed=values.filter((value,i)=>value!==capped[i]).length;setModified(rows.map((r,i)=>({...r,[activeFeature]:capped[i]})));setStatus(`Capped ${changed} values at ${method==='iqr'?'IQR':'Z-score'} fences`)};
 const n=rows.length,share=(x:number)=>(x/Math.max(1,n)*100).toFixed(1),displayTotal=n,displayMild=counts.mild,displaySevere=counts.severe,displayNormal=counts.normal,severe=results.map((r,i)=>({...r,index:i,x:values[i],y:pvals[i]})).filter(r=>r.band==='severe').sort((a,b)=>b.score-a.score).slice(0,5),normalValues=values.filter((_,i)=>results[i].band==='normal'),meanDrop=normalValues.length?(1-mean(normalValues)/Math.max(.001,mean(values)))*100:0,stdDrop=normalValues.length?(1-std(normalValues)/Math.max(.001,std(values)))*100:0;
 const compare = useMemo(() => {
   const tally = (xs: OutlierResult[]) => ({
     mild: xs.filter((x) => x.band === "mild").length,
     severe: xs.filter((x) => x.band === "severe").length,
     flagged: xs.filter((x) => x.band !== "normal").length,
   });
   return {
     iqr: tally(detectOutliers(values, "iqr", multiplier)),
     zscore: tally(detectOutliers(values, "zscore", multiplier)),
   };
 }, [values, multiplier]);
 const probeScore=method==='iqr'?(probe<q1?(q1-probe)/(iqr||1):probe>q3?(probe-q3)/(iqr||1):0):Math.abs((probe-center)/(spread||1));const probeBand=probeScore>multiplier*2?'severe':probeScore>multiplier?'mild':'normal';
 const previewRows = rows.slice(0, 16);
 const stage =
   tab === "Learn"
     ? 1
     : tab === "Transform"
       ? 3
       : ["Metrics", "Compare", "Live Test / Inference"].includes(tab)
         ? 4
         : 2;
 return <div className={`od-page ${collapsed?'collapsed':''}`}><aside className="od-side"><a className="brand" href="/"><i>◇</i><b>Mega ML<small>AI Observatory</small></b></a><button className="home" onClick={()=>go('Home')}>⌂　Home</button>{['▣　Data','⌁　Explore','♙　Train','◉　Evaluate','◇　Deploy','♙　MLOps','◇　Registry','⚙　Settings'].map(x=><button key={x} onClick={()=>go(x)}>{x}</button>)}<button className="collapse" onClick={()=>setCollapsed(v=>!v)}>≪　Collapse</button></aside>
 <header className="od-head"><h1><i>♙</i> Outlier Detection</h1><label>Dataset<select aria-label="Dataset" value={uploaded?'uploaded':dataset} onChange={e=>chooseDataset(+e.target.value)}>{DATASETS.map((d,i)=><option value={i} key={d.name}>{d.name}</option>)}{uploaded&&<option value="uploaded">{uploaded.name}</option>}</select></label><button onClick={()=>fileRef.current?.click()}>⇧　Upload CSV</button><input ref={fileRef} type="file" hidden accept=".csv,text/csv" onChange={e=>void upload(e.target.files?.[0])}/></header>
 <section className="od-objective"><article><small>OBJECTIVE</small><p>Learn and apply unsupervised techniques to detect, visualize, and manage anomalous observations that deviate from normal behavior.</p></article><article><small>YOUR PROGRESS</small><div>{stage===1?<><b>① Learn</b>　━━　② Visualize　━━　③ Transform　━━　④ Evaluate</>:stage===3?<>① Learn　━━　② Visualize　━━　<b>③ Transform</b>　━━　④ Evaluate</>:stage===4?<>① Learn　━━　② Visualize　━━　③ Transform　━━　<b>④ Evaluate</b></>:<>① Learn　━━　<b>② Visualize</b>　━━　③ Transform　━━　④ Evaluate</>}</div></article></section>
 <section className="od-work"><nav role="tablist" aria-label="Outlier detection sections">{TABS.map(x=><button type="button" role="tab" aria-selected={tab===x} className={tab===x?'active':''} key={x} onClick={()=>{setTab(x);setStatus(`${x} view selected`)}}>{x}</button>)}</nav>{tab==='Visualize'?<><div className="plots"><article className="scatter panel"><h2>Scatter: {activeFeature} vs {partner}　ⓘ</h2><div className="legend"><span>● Normal</span><span>● Mild Outlier</span><span>★ Severe Outlier</span><span>◯ Selected</span></div><svg viewBox="0 0 430 315" role="img" aria-label={`All ${n} observations plotted by outlier class`}><g className="grid">{[40,100,160,220,280].map(y=><line key={y} x1="45" x2="415" y1={y} y2={y}/>)}</g>{rows.map((r,ri)=>{const band=results[ri].band,x=45+(r[activeFeature]-min)/(max-min||1)*365,py=Math.min(...pvals),px=Math.max(...pvals),y=290-(r[partner]-py)/(px-py||1)*260;return <circle className={`${band} ${inspect&&band!=='normal'?'selected':''}`} key={ri} cx={x} cy={y} r={band==='severe'?3.7:band==='mild'?2.8:2}><title>Row {ri+1}: {activeFeature} {r[activeFeature].toFixed(2)}, {partner} {r[partner].toFixed(2)}, {band}, score {results[ri].score.toFixed(2)}</title></circle>})}<text x="45" y="306">{min.toFixed(1)}</text><text x="380" y="306">{max.toFixed(1)}</text><text x="205" y="315">{activeFeature}</text><text transform="rotate(-90 12 180)" x="12" y="180">{partner}</text></svg><small>N = {n.toLocaleString()} · all rows shown</small></article>
 <article className="box panel"><h2>Boxplot: {activeFeature}　ⓘ</h2><svg viewBox="0 0 400 315" role="img" aria-label="Quartiles, median, active fences, and flagged values"><line className="whisker" x1="45" x2="380" y1="160" y2="160"/><rect className="quartile-box" x={chartX(q1)} y="130" width={Math.max(1,chartX(q3)-chartX(q1))} height="60"/><line className="median" x1={chartX(med)} x2={chartX(med)} y1="130" y2="190"/>{[{v:lower,n:'Lower fence'},{v:upper,n:'Upper fence'}].filter(x=>x.v>=min&&x.v<=max).map(x=><g key={x.n}><line className="fence" x1={chartX(x.v)} x2={chartX(x.v)} y1="85" y2="220"/><title>{x.n}: {x.v.toFixed(2)}</title></g>)}{results.map((r,i)=>r.band==='normal'?null:<circle className={r.band} key={i} cx={chartX(r.value)} cy={160+((i%5)-2)*7} r="3"><title>Row {i+1}: {r.value.toFixed(2)} ({r.band})</title></circle>)}<text x="45" y="260">Min {min.toFixed(1)}</text><text x="380" y="260" textAnchor="end">Max {max.toFixed(1)}</text><text x="45" y="287">Q1 {q1.toFixed(1)} · Median {med.toFixed(1)} · Q3 {q3.toFixed(1)}</text><text x="45" y="307">Active fences: {lower.toFixed(1)} to {upper.toFixed(1)}</text></svg></article>
 <article className="distribution panel"><h2>Distribution: {activeFeature}</h2><svg viewBox="0 0 420 315" role="img" aria-label="Histogram of all observations, stacked by normal, mild, and severe classification"><g className="grid">{[50,110,170,230].map(y=><line key={y} x1="30" x2="405" y1={y} y2={y}/>)}</g>{histBands.map((bin,i)=>{const x=30+i*11.7,h1=bin.normal/histPeak*220,h2=bin.mild/histPeak*220,h3=bin.severe/histPeak*220;return <g key={i}><rect className="normal" x={x} y={255-h1} width="10" height={h1}/><rect className="mild" x={x} y={255-h1-h2} width="10" height={h2}/><rect className="severe" x={x} y={255-h1-h2-h3} width="10" height={h3}/><title>Bin {i+1}: {bin.normal} normal, {bin.mild} mild, {bin.severe} severe</title></g>})}<text x="30" y="282">{min.toFixed(1)}</text><text x="405" y="282" textAnchor="end">{max.toFixed(1)}</text><text x="210" y="305" textAnchor="middle">{activeFeature}</text></svg><p className="chart-caption">Each bar counts observations; colors use the active {method==='iqr'?'IQR':'Z-score'} rule.</p></article></div>
 <section className="insights"><h3>LINKED INSIGHTS</h3><div><article><b>Outlier Summary</b><div className="donut" style={{background:`conic-gradient(#38cbd1 0 ${+share(counts.normal)}%,#f5b83c 0 ${+(share(counts.normal))+ +share(counts.mild)}%,#ff6666 0)`}}><i>{displayMild+displaySevere}<small>Outliers</small></i></div><p>■ Normal　{share(counts.normal)}%</p><p>■ Mild　{share(counts.mild)}%</p><p>■ Severe　{share(counts.severe)}%</p></article><article><b>Extreme Points <small>(Top 5 by {activeFeature})</small></b><table><thead><tr><th>Index</th><th>{activeFeature}</th><th>{partner}</th><th>AQI</th></tr></thead><tbody>{severe.map(x=><tr key={x.index}><td>{x.index+1}</td><td>{x.x.toFixed(1)}</td><td>{x.y.toFixed(1)}</td><td><em>{rows[x.index].AQI?.toFixed(0)??'—'}</em></td></tr>)}</tbody></table></article><article><b>Feature Correlation <small>(vs {activeFeature})</small></b>{features.filter(f=>f!==activeFeature).slice(0,5).map(f=>{const c=correlation(values,rows.map(row=>row[f]));return <p key={f}>{f.split(' ')[0]}<i><span style={{width:`${Math.abs(c)*100}%`}}/></i>{c.toFixed(2)}</p>})}</article><article><b>Outlier Impact</b><p>Removing flagged outliers changes mean {activeFeature} by <strong>{meanDrop.toFixed(1)}%</strong> and standard deviation by <strong>{stdDrop.toFixed(1)}%</strong>.</p></article><article><b>What’s Next?</b><p>✓ Inspect outliers to understand causes</p><p>✓ Compare methods (IQR vs Z-Score)</p><p>⊙ Apply transformation and re-evaluate</p><button type="button" onClick={()=>{setTab('Transform');setStatus('Transform view selected')}}>Go to Transform　→</button></article></div></section></>:<div className="od-tab-body">
 {tab==='Learn'&&<div className="od-copy"><article className="panel"><h2>What is an outlier?</h2><p>An outlier is a point that sits far from the rest of the distribution. In this lab, fences come from either IQR or Z-score, then each observation is labeled normal, mild, or severe.</p></article><article className="panel"><h2>IQR fences</h2><p>Q1 and Q3 split the feature into quartiles. The fence is Q1 − k·IQR and Q3 + k·IQR. Raising k is more conservative; lowering k flags more points.</p></article><article className="panel"><h2>Z-score fences</h2><p>Z-score is |x − mean| / std. Values above k are mild; values above 2k are severe. This method is more sensitive to extreme tails than IQR when the data is skewed.</p></article><article className="panel"><h2>What to try</h2><p>Switch method in the right panel, then open Visualize to see scatter, boxplot, and histogram update together. Use Transform when you want to remove or cap the flagged rows.</p><button type="button" onClick={()=>{setTab('Visualize');setStatus('Visualize view selected')}}>Open Visualize →</button></article></div>}
 {tab==='Dataset'&&<article className="panel od-data-wrap"><h2>Dataset preview · {activeFeature}</h2><p>First {previewRows.length} of {n.toLocaleString()} rows. Flagged rows use the active method ({method === 'iqr' ? 'IQR' : 'Z-score'}, k={multiplier}).</p><div className="od-data-scroll"><table className="od-data-table"><thead><tr><th>#</th><th>{activeFeature}</th><th>{partner}</th><th>AQI</th><th>Band</th></tr></thead><tbody>{previewRows.map((row, i) => <tr key={i} className={results[i]?.band}><td>{i + 1}</td><td>{row[activeFeature]?.toFixed(2)}</td><td>{row[partner]?.toFixed(2)}</td><td>{row.AQI?.toFixed(0) ?? '—'}</td><td>{results[i]?.band ?? '—'}</td></tr>)}</tbody></table></div></article>}
 {tab==='Transform'&&<div className="od-copy"><article className="panel"><h2>Apply a transform</h2><p>{counts.mild + counts.severe} of {n} observations are flagged on {activeFeature}. Remove drops those rows. Cap at fences keeps every row but clips values at the active method fences.</p><div className="od-actions">{[{label:'Remove outliers',run:remove},{label:'Cap at fences',run:cap},{label:'Reset data',run:reset}].map(action => <button type="button" key={action.label} onClick={action.run}>{action.label}</button>)}</div></article><article className="panel"><h2>Current impact</h2><p>Removing flagged points would change mean {activeFeature} by {meanDrop.toFixed(1)}% and standard deviation by {stdDrop.toFixed(1)}%.</p><p>{modified ? 'A transformed copy is active. Reset restores the original sample or upload.' : 'You are still on the original rows.'}</p></article></div>}
 {tab==='Metrics'&&<div className="od-copy od-metrics"><article className="panel"><h2>Normal</h2><b>{share(counts.normal)}%</b><p>{displayNormal.toLocaleString()} observations stay inside the fences.</p></article><article className="panel"><h2>Mild</h2><b>{share(counts.mild)}%</b><p>{displayMild.toLocaleString()} points sit between k and 2k.</p></article><article className="panel"><h2>Severe</h2><b>{share(counts.severe)}%</b><p>{displaySevere.toLocaleString()} points sit beyond 2k.</p></article><article className="panel"><h2>If removed</h2><b>{meanDrop.toFixed(1)}%</b><p>Mean change on {activeFeature}. Std would drop {stdDrop.toFixed(1)}%.</p></article></div>}
 {tab==='Compare'&&<div className="od-copy od-compare"><article className="panel"><h2>IQR (k={multiplier})</h2><p>Flagged {compare.iqr.flagged.toLocaleString()} rows ({share(compare.iqr.flagged)}%). Mild {compare.iqr.mild}, severe {compare.iqr.severe}.</p></article><article className="panel"><h2>Z-score (k={multiplier})</h2><p>Flagged {compare.zscore.flagged.toLocaleString()} rows ({share(compare.zscore.flagged)}%). Mild {compare.zscore.mild}, severe {compare.zscore.severe}.</p></article><article className="panel"><h2>How to read this</h2><p>IQR is robust to a few extreme spikes. Z-score uses mean and std, so one huge spike can pull the fence. Active method: {method === 'iqr' ? 'IQR' : 'Z-score'}.</p></article></div>}
 {tab==='Live Test / Inference'&&<div className="od-copy"><article className="panel"><h2>Test a new {activeFeature} value</h2><p>Apply the current dataset statistics to a new value. This test does not add a row or change the reference statistics.</p><label className="od-probe">Value <input type="number" value={probe} onChange={e=>setProbe(Number(e.target.value))}/></label><p className="od-probe-result">Result: <strong>{probeBand}</strong> · score {probeScore.toFixed(2)}</p></article><article className="panel"><h2>How it is classified</h2><p>{method==='iqr'?'Using the current quartiles and IQR.':'Using the current mean and standard deviation.'} Score above {multiplier.toFixed(1)} is mild; above {(multiplier*2).toFixed(1)} is severe.</p><p>Q1 {q1.toFixed(2)} · median {med.toFixed(2)} · Q3 {q3.toFixed(2)} · active fences {lower.toFixed(2)} to {upper.toFixed(2)}.</p><p>An outlier is a signal to investigate, not automatically a bad row.</p></article></div>}
 </div>}</section>
 <aside className="od-controls"><small>OUTLIER DETECTION　ⓘ</small><label>Method<div className="method"><button className={method==='iqr'?'active':''} onClick={()=>setMethod('iqr')}>IQR</button><button className={method==='zscore'?'active':''} onClick={()=>setMethod('zscore')}>Z-Score</button></div></label><label>Feature<select aria-label="Feature" value={activeFeature} onChange={e=>setFeature(e.target.value)}>{features.map(f=><option key={f}>{f}</option>)}</select></label><b>{method==='iqr'?'IQR Settings':'Z-Score Settings'}</b><label>Multiplier (k)<div className="step"><button onClick={()=>setMultiplier(v=>Math.max(.5,+(v-.1).toFixed(1)))}>−</button><input aria-label="Outlier multiplier" type="number" min="0.5" max="4" step="0.1" value={multiplier} onChange={e=>{const next=Number(e.target.value);if(Number.isFinite(next)&&next>=.5&&next<=4)setMultiplier(next)}}/><button onClick={()=>setMultiplier(v=>Math.min(4,+(v+.1).toFixed(1)))}>＋</button></div></label><p>Outliers outside the active statistical fences are flagged.</p><section className="results"><b>Results</b><p>Total Observations <strong>{displayTotal.toLocaleString()}</strong></p><p className="normal">Normal <strong>{displayNormal.toLocaleString()} ({share(counts.normal)}%)</strong></p><p className="mild">Mild Outliers <strong>{displayMild.toLocaleString()} ({share(counts.mild)}%)</strong></p><p className="severe">Severe Outliers <strong>{displaySevere.toLocaleString()} ({share(counts.severe)}%)</strong></p></section><b>Actions</b><button className="remove" onClick={remove}>♲　Remove Outliers</button><button className="cap" onClick={cap}>♨　Cap at Fences</button><button className="inspect" onClick={()=>{setInspect(v=>!v);setStatus('Flagged observations inspected')}}>◉　Inspect Outliers</button><button onClick={reset}>↻　Reset</button><a href="?advanced=1">Open original outlier workbench →</a></aside>
 <footer className="od-footer">Dataset: {uploaded?.name??DATASETS[dataset].name}　 |　 Rows: {n.toLocaleString()}　 |　 Numeric columns: {features.length}　 |　 {uploaded?'Uploaded data':'Synthetic teaching data'}<span role="status">◉　{status}</span></footer></div>
}
