/* eslint-disable no-irregular-whitespace, react-hooks/preserve-manual-memoization */
import { useMemo, useRef, useState } from 'react';
import { useLabNavigate } from '../../../lib/labNavigation';
import { mean, quantile, std } from '../../../lib/math/statistics';
import { capAtIqrFences, detectOutliers, type OutlierMethod } from '../../../lib/preprocessing/outlierDetection';
import './OutlierDetectionApprovedPage.css';

type Row=Record<string,number>; const TABS=['Learn','Visualize','Dataset','Transform','Metrics','Compare','Explain'];
const FEATURES=['PM2.5 (µg/m³)','PM10 (µg/m³)','NO2 (ppb)','O3 (ppb)','CO (ppm)','SO2 (ppb)','AQI'];
function seeded(seed:number){let s=seed>>>0;return()=>((s=(s*1664525+1013904223)>>>0)/4294967296)}
function makeRows(seed:number,n=520){const r=seeded(seed);return Array.from({length:n},(_,i)=>{const spike=i%47===0?80+r()*90:i%29===0?35+r()*40:0,pm25=Math.max(2,8+Math.pow(r(),2.2)*48+spike),pm10=pm25*(1.45+r()*.55)+r()*15;return {'PM2.5 (µg/m³)':pm25,'PM10 (µg/m³)':pm10,'NO2 (ppb)':12+r()*45+spike*.16,'O3 (ppb)':18+r()*42-spike*.04,'CO (ppm)':.2+r()*1.1+spike*.005,'SO2 (ppb)':2+r()*18+spike*.08,AQI:Math.min(300,pm25*1.3+pm10*.35)}})}
const DATASETS=[{name:'Seattle Air Quality (WA)',rows:4356,columns:12,date:'Jan 1 – Dec 31, 2023',data:makeRows(74)},{name:'NYC Sensor Network',rows:8760,columns:10,date:'Jan 1 – Dec 31, 2024',data:makeRows(88)},{name:'Delhi Air Monitor',rows:5256,columns:14,date:'Jul 1 – Dec 31, 2025',data:makeRows(103)}];
const path=(values:number[],w:number,h:number)=>{const max=Math.max(...values,1);return values.map((v,i)=>`${i?'L':'M'}${(i/(values.length-1||1)*w).toFixed(1)},${(h-v/max*h).toFixed(1)}`).join(' ')};

export default function OutlierDetectionApprovedPage(){
 const [dataset,setDataset]=useState(0),[uploaded,setUploaded]=useState<{name:string;rows:Row[]}|null>(null),[method,setMethod]=useState<OutlierMethod>('iqr'),[feature,setFeature]=useState(FEATURES[0]),[multiplier,setMultiplier]=useState(1.5),[tab,setTab]=useState('Visualize'),[inspect,setInspect]=useState(false),[newVersion,setNewVersion]=useState(true),[status,setStatus]=useState('All changes saved'),[collapsed,setCollapsed]=useState(false),[modified,setModified]=useState<Row[]|null>(null);const fileRef=useRef<HTMLInputElement>(null);const go=useLabNavigate();
 const rows=modified??uploaded?.rows??DATASETS[dataset].data,features=Object.keys(rows[0]??{}),activeFeature=features.includes(feature)?feature:features[0],values=rows.map(r=>r[activeFeature]),results=useMemo(()=>detectOutliers(values,method,multiplier),[values,method,multiplier]),counts={normal:results.filter(x=>x.band==='normal').length,mild:results.filter(x=>x.band==='mild').length,severe:results.filter(x=>x.band==='severe').length};
 const q1=quantile(values,.25),q3=quantile(values,.75),med=quantile(values,.5),iqr=q3-q1,lower=q1-multiplier*iqr,upper=q3+multiplier*iqr,max=Math.max(...values),min=Math.min(...values),partner=features.find(f=>f!==activeFeature)??activeFeature,pvals=rows.map(r=>r[partner]);
 const bins=useMemo(()=>{const count=48,out=Array(count).fill(0);values.forEach(v=>out[Math.min(count-1,Math.floor((v-min)/(max-min||1)*count))]++);return out},[values,min,max]);
 const upload=async(file?:File)=>{if(!file)return;const lines=(await file.text()).trim().split(/\r?\n/),hs=lines[0].split(',').map(x=>x.trim()),parsed=lines.slice(1).map(line=>line.split(',').map(Number)).filter(v=>v.length===hs.length&&v.every(Number.isFinite)).map(v=>Object.fromEntries(hs.map((h,i)=>[h,v[i]])));if(parsed.length<8){setStatus('CSV needs at least 8 complete numeric rows');return}setUploaded({name:file.name,rows:parsed});setModified(null);setFeature(hs[0]);setStatus(`${file.name} · ${parsed.length} rows loaded`)};
 const chooseDataset=(i:number)=>{setDataset(i);setUploaded(null);setModified(null);setFeature(FEATURES[0]);setStatus(`${DATASETS[i].name} loaded`)};const reset=()=>{setMethod('iqr');setFeature(FEATURES[0]);setMultiplier(1.5);setInspect(false);setModified(null);setStatus('Outlier view reset')};
 const remove=()=>{setModified(rows.filter((_,i)=>results[i].band==='normal'));setStatus(`Removed ${counts.mild+counts.severe} flagged observations`)};const cap=()=>{const capped=capAtIqrFences(values,multiplier);setModified(rows.map((r,i)=>({...r,[activeFeature]:capped[i]})));setStatus(`Capped ${counts.mild+counts.severe} observations at IQR fences`)};
 const n=rows.length,share=(x:number)=>(x/Math.max(1,n)*100).toFixed(1),displayTotal=uploaded||modified?n:DATASETS[dataset].rows,displayMild=Math.round(counts.mild/n*displayTotal),displaySevere=Math.round(counts.severe/n*displayTotal),displayNormal=displayTotal-displayMild-displaySevere,severe=results.map((r,i)=>({...r,index:i,x:values[i],y:pvals[i]})).filter(r=>r.band==='severe').sort((a,b)=>b.value-a.value).slice(0,5),normalValues=values.filter((_,i)=>results[i].band==='normal'),meanDrop=(1-mean(normalValues)/Math.max(.001,mean(values)))*100,stdDrop=(1-std(normalValues)/Math.max(.001,std(values)))*100;
 return <div className={`od-page ${collapsed?'collapsed':''}`}><aside className="od-side"><a className="brand" href="/"><i>◇</i><b>Mega ML<small>AI Observatory</small></b></a><button className="home" onClick={()=>go('Home')}>⌂　Home</button>{['▣　Data','⌁　Explore','♙　Train','◉　Evaluate','◇　Deploy','♙　MLOps','◇　Registry','⚙　Settings'].map(x=><button key={x} onClick={()=>go(x)}>{x}</button>)}<button className="collapse" onClick={()=>setCollapsed(v=>!v)}>≪　Collapse</button></aside>
 <header className="od-head"><h1><i>♙</i> Outlier Detection</h1><label>Dataset<select aria-label="Dataset" value={dataset} onChange={e=>chooseDataset(+e.target.value)}>{DATASETS.map((d,i)=><option value={i} key={d.name}>{d.name}</option>)}</select></label><button onClick={()=>fileRef.current?.click()}>⇧　Upload CSV</button><input ref={fileRef} type="file" hidden accept=".csv,text/csv" onChange={e=>void upload(e.target.files?.[0])}/><button onClick={()=>setStatus('Theme toggled')}>☼</button><button onClick={()=>go('Help')}>?</button><button onClick={()=>setStatus('Profile opened')}>ML</button></header>
 <section className="od-objective"><article><small>OBJECTIVE</small><p>Learn and apply unsupervised techniques to detect, visualize, and manage anomalous observations that deviate from normal behavior.</p></article><article><small>YOUR PROGRESS</small><div>① Learn　━━　<b>② Visualize</b>　━━　③ Transform　━━　④ Evaluate</div></article></section>
 <section className="od-work"><nav>{TABS.map((x,i)=><button className={tab===x?'active':''} key={x} onClick={()=>{setTab(x);setStatus(`${x} view selected`)}}>{['◇','♙','▣','↔','⌁','⌘','◎'][i]}　{x}</button>)}</nav><div className="plots"><article className="scatter panel"><h2>Scatter: {activeFeature} vs {partner}　ⓘ</h2><div className="legend"><span>● Normal</span><span>● Mild Outlier</span><span>★ Severe Outlier</span><span>◯ Selected</span></div><svg viewBox="0 0 430 315" role="img" aria-label="Outlier scatter plot"><g className="grid">{[40,100,160,220,280].map(y=><line key={y} x1="45" x2="415" y1={y} y2={y}/>)}</g>{rows.filter((_,i)=>i%2===0).map((r,i)=>{const ri=i*2,band=results[ri].band,x=45+(r[activeFeature]-min)/(max-min||1)*365,py=Math.min(...pvals),px=Math.max(...pvals),y=290-(r[partner]-py)/(px-py||1)*260;return band==='severe'?<path className={band} key={ri} d={`M${x-4},${y}l2.5,-2.5l-1,-4l3.5,2l3.5,-2l-1,4l2.5,2.5l-4,1l-1,4l-2,-3.5l-4,1.5z`}/>:<circle className={`${band} ${inspect&&band!=='normal'?'selected':''}`} key={ri} cx={x} cy={y} r={band==='mild'?2.8:2}/>} )}<text x="205" y="311">{activeFeature}</text><text transform="rotate(-90 12 180)" x="12" y="180">{partner}</text></svg><small>N = {(uploaded?.rows.length??DATASETS[dataset].rows).toLocaleString()}</small><div className="tools"><button onClick={()=>setStatus('Zoomed into scatter')}>⌕</button><button onClick={()=>setStatus('Scatter captured')}>▧</button><button onClick={()=>setInspect(v=>!v)}>⌗</button><button onClick={()=>setStatus('Scatter view reset')}>↻</button></div></article>
 <article className="box panel"><h2>Boxplot: {activeFeature}　ⓘ</h2><svg viewBox="0 0 300 360" role="img" aria-label="Outlier boxplot"><line x1="90" x2="210" y1={310-(Math.max(min,lower)-min)/(max-min||1)*270} y2={310-(Math.max(min,lower)-min)/(max-min||1)*270}/><rect x="90" width="120" y={310-(q3-min)/(max-min||1)*270} height={Math.max(5,iqr/(max-min||1)*270)}/><line className="median" x1="90" x2="210" y1={310-(med-min)/(max-min||1)*270} y2={310-(med-min)/(max-min||1)*270}/><line className="fence" x1="40" x2="255" y1={310-(Math.min(max,upper)-min)/(max-min||1)*270} y2={310-(Math.min(max,upper)-min)/(max-min||1)*270}/>{results.filter(x=>x.band!=='normal').slice(0,35).map((r,i)=><circle className={r.band} key={i} cx={130+(i%5)*9} cy={310-(r.value-min)/(max-min||1)*270} r="3"/>)}<text x="220" y={314-(q3-min)/(max-min||1)*270}>Q3 ({q3.toFixed(1)})</text><text x="220" y={314-(med-min)/(max-min||1)*270}>Median ({med.toFixed(1)})</text><text x="220" y={314-(q1-min)/(max-min||1)*270}>Q1 ({q1.toFixed(1)})</text><text x="210" y={306-(Math.min(max,upper)-min)/(max-min||1)*270}>Upper Fence ({upper.toFixed(1)})</text></svg></article>
 <article className="distribution panel"><h2>Distribution: {activeFeature}</h2><svg viewBox="0 0 420 330" role="img" aria-label="Outlier distribution"><path className="area" d={`${path(bins,390,260)} L390,270 L0,270 Z`}/><path className="curve" d={path(bins,390,260)}/>{[{v:q1,n:'Q1'},{v:med,n:'Median'},{v:q3,n:'Q3'},{v:upper,n:'Upper Fence'}].map(x=><g key={x.n}><line x1={(x.v-min)/(max-min||1)*390} x2={(x.v-min)/(max-min||1)*390} y1="5" y2="275"/><text x={(x.v-min)/(max-min||1)*390+3} y="12">{x.n}</text></g>)}</svg><div className="brush">{bins.map((v,i)=><i key={i} style={{height:`${Math.max(2,v/Math.max(...bins)*28)}px`}}/> )}</div></article></div>
 <section className="insights"><h3>LINKED INSIGHTS</h3><div><article><b>Outlier Summary</b><div className="donut" style={{background:`conic-gradient(#38cbd1 0 ${+share(counts.normal)}%,#f5b83c 0 ${+(share(counts.normal))+ +share(counts.mild)}%,#ff6666 0)`}}><i>{displayMild+displaySevere}<small>Outliers</small></i></div><p>■ Normal　{share(counts.normal)}%</p><p>■ Mild　{share(counts.mild)}%</p><p>■ Severe　{share(counts.severe)}%</p></article><article><b>Extreme Points <small>(Top 5 by {activeFeature})</small></b><table><thead><tr><th>Index</th><th>{activeFeature}</th><th>{partner}</th><th>AQI</th></tr></thead><tbody>{severe.map(x=><tr key={x.index}><td>{x.index+1}</td><td>{x.x.toFixed(1)}</td><td>{x.y.toFixed(1)}</td><td><em>{rows[x.index].AQI?.toFixed(0)??'—'}</em></td></tr>)}</tbody></table></article><article><b>Feature Correlation <small>(vs {activeFeature})</small></b>{features.slice(1,6).map((f,i)=><p key={f}>{f.split(' ')[0]}<i><span style={{width:`${88-i*13}%`}}/></i>{(0.89-i*.17).toFixed(2)}</p>)}</article><article><b>Outlier Impact</b><p>Removing flagged outliers reduces mean {activeFeature} by <strong>{meanDrop.toFixed(1)}%</strong> and standard deviation by <strong>{stdDrop.toFixed(1)}%</strong>.</p></article><article><b>What’s Next?</b><p>✓ Inspect outliers to understand causes</p><p>✓ Compare methods (IQR vs Z-Score)</p><p>⊙ Apply transformation and re-evaluate</p><button onClick={()=>setStatus('Transform workspace opened')}>Go to Transform　→</button></article></div></section></section>
 <aside className="od-controls"><small>OUTLIER DETECTION　ⓘ</small><label>Method<div className="method"><button className={method==='iqr'?'active':''} onClick={()=>setMethod('iqr')}>IQR</button><button className={method==='zscore'?'active':''} onClick={()=>setMethod('zscore')}>Z-Score</button></div></label><label>Feature<select aria-label="Feature" value={activeFeature} onChange={e=>setFeature(e.target.value)}>{features.map(f=><option key={f}>{f}</option>)}</select></label><b>{method==='iqr'?'IQR Settings':'Z-Score Settings'}</b><label>Multiplier (k)<div className="step"><button onClick={()=>setMultiplier(v=>Math.max(.5,+(v-.1).toFixed(1)))}>−</button><input aria-label="Outlier multiplier" type="number" min="0.5" max="4" step="0.1" value={multiplier} onChange={e=>setMultiplier(+e.target.value)}/><button onClick={()=>setMultiplier(v=>Math.min(4,+(v+.1).toFixed(1)))}>＋</button></div></label><p>Outliers outside the active statistical fences are flagged.</p><section className="results"><b>Results</b><p>Total Observations <strong>{displayTotal.toLocaleString()}</strong></p><p className="normal">Normal <strong>{displayNormal.toLocaleString()} ({share(counts.normal)}%)</strong></p><p className="mild">Mild Outliers <strong>{displayMild.toLocaleString()} ({share(counts.mild)}%)</strong></p><p className="severe">Severe Outliers <strong>{displaySevere.toLocaleString()} ({share(counts.severe)}%)</strong></p></section><b>Actions</b><button className="remove" onClick={remove}>♲　Remove Outliers</button><button className="cap" onClick={cap}>♨　Cap at Fences</button><button className="inspect" onClick={()=>{setInspect(v=>!v);setStatus('Flagged observations inspected')}}>◉　Inspect Outliers</button><button onClick={reset}>↻　Reset</button><a href="?advanced=1">Open original outlier workbench →</a><label className="version">Apply to Dataset <span>Create new version　<input aria-label="Create new version" type="checkbox" checked={newVersion} onChange={e=>setNewVersion(e.target.checked)}/></span></label></aside>
 <footer className="od-footer">Dataset: {uploaded?.name??DATASETS[dataset].name}　 |　 Rows: {(modified?.length??uploaded?.rows.length??DATASETS[dataset].rows).toLocaleString()}　 |　 Columns: {uploaded?features.length:DATASETS[dataset].columns}　 |　 Date Range: {uploaded?'Imported data':DATASETS[dataset].date}　 |　 Target: AQI (Air Quality Index)<span>◉　{status}</span></footer></div>
}
