/* eslint-disable no-irregular-whitespace */
import { useMemo, useRef, useState } from 'react';
import { useLabNavigate } from '../../../lib/labNavigation';
import { mean, median, quantile, std } from '../../../lib/math/statistics';
import { LabLessonOrWork, labHide } from '../../../components/common/LabTabs';
import './ScalingApprovedPage.css';

type Method='zscore'|'minmax'|'robust';
type DatasetKey='Wine Quality (White)'|'Breast Cancer Wisconsin'|'Diabetes Progression';
type Row=Record<string,number>;
const DATASETS:Record<DatasetKey,{rows:number;features:string[]}>= {
  'Wine Quality (White)':{rows:4898,features:['Alcohol','Malic Acid','Total Sulfur Dioxide','pH','Ash','Alcalinity of Ash','Magnesium','Total Phenols','Flavanoids','Color Intensity','Density']},
  'Breast Cancer Wisconsin':{rows:569,features:['Mean Radius','Mean Texture','Mean Perimeter','Mean Area','Mean Smoothness','Mean Compactness','Mean Concavity','Radius Error','Worst Radius','Worst Texture','Worst Area']},
  'Diabetes Progression':{rows:442,features:['Age','BMI','Blood Pressure','Serum 1','Serum 2','Serum 3','Serum 4','Serum 5','Serum 6','Sex','Progression']},
};
const DISPLAY_LABELS=['Alcohol','Malic Acid','Total Sulfur Dioxide','pH'];
function seededValue(index:number,salt:number){const n=Math.sin((index+1)*19.17+salt*43.31)*43758.5453;return n-Math.floor(n)}
function generate(key:DatasetKey):Row[]{const fs=DATASETS[key].features;return Array.from({length:180},(_,i)=>Object.fromEntries(fs.map((f,j)=>{const a=seededValue(i,j+key.length),b=seededValue(i,j*2+7);let value:number;if(key==='Wine Quality (White)'){const scales=[4,2.4,400,1.4,1.6,5,120,9,90,10,.03];const offsets=[8,0,0,2.5,1,25,20,0,20,1,.99];value=offsets[j]+(a+b+b)/3*scales[j]}else if(key==='Breast Cancer Wisconsin'){value=5+(a+b+b)/3*(j%3===0?30:12)}else value=-.12+(a+b+b)/3*.25;return [f,value]})))}
function scale(values:number[],method:Method){if(method==='minmax'){const lo=Math.min(...values),hi=Math.max(...values);return values.map(v=>(v-lo)/(hi-lo||1))}if(method==='robust'){const med=median(values),iq=quantile(values,.75)-quantile(values,.25);return values.map(v=>(v-med)/(iq||1))}const m=mean(values),s=std(values);return values.map(v=>(v-m)/(s||1))}
function pairedBins(raw:number[],scaled:number[],count=28){const lo=Math.min(...raw,...scaled),hi=Math.max(...raw,...scaled),width=(hi-lo||1)/count;const make=(values:number[])=>{const counts=Array(count).fill(0);values.forEach(v=>counts[Math.min(count-1,Math.max(0,Math.floor((v-lo)/width)))]++);const high=Math.max(...counts,1);return counts.map((c,i)=>({x:i/(count-1),y:c/high}))};return{raw:make(raw),scaled:make(scaled)}}
function path(points:{x:number;y:number}[],w=208,h=83){return points.map((p,i)=>`${i?'L':'M'}${(12+p.x*(w-24)).toFixed(1)},${(h-9-p.y*(h-20)).toFixed(1)}`).join(' ')}
function pairedScatter(x:number[],y:number[],method:Method){const sx=scale(x,method),sy=scale(y,method),xmin=Math.min(...x,...sx),xmax=Math.max(...x,...sx),ymin=Math.min(...y,...sy),ymax=Math.max(...y,...sy);const project=(xs:number[],ys:number[])=>xs.slice(0,110).map((v,i)=>({x:10+(v-xmin)/(xmax-xmin||1)*192,y:94-(ys[i]-ymin)/(ymax-ymin||1)*82}));return{raw:project(x,y),scaled:project(sx,sy)}}
const TABS=['Learn','Visualize','Dataset','Transform','Train','Metrics','Compare','Explain'];
export default function ScalingApprovedPage(){
 const [dataset,setDataset]=useState<DatasetKey>('Wine Quality (White)');const [uploaded,setUploaded]=useState<{name:string;rows:Row[];features:string[]}|null>(null);const [method,setMethod]=useState<Method>('zscore');const [activeTab,setActiveTab]=useState('Learn');const [custom,setCustom]=useState(false);const [selected,setSelected]=useState<string[]>(DATASETS['Wine Quality (White)'].features);const [search,setSearch]=useState('');const [density,setDensity]=useState(true);const [scatter,setScatter]=useState(true);const [linkAxes,setLinkAxes]=useState(true);const [logScale,setLogScale]=useState(false);const [status,setStatus]=useState('Ready');const [collapsed,setCollapsed]=useState(false);const fileRef=useRef<HTMLInputElement>(null);const go=useLabNavigate();
 const rows=useMemo(()=>uploaded?.rows??generate(dataset),[uploaded,dataset]);const features=uploaded?.features??DATASETS[dataset].features;const visibleFeatures=features.filter(f=>f.toLowerCase().includes(search.toLowerCase()));const chosen=custom?selected.filter(f=>features.includes(f)):features;const preferred=DISPLAY_LABELS.filter(feature=>chosen.includes(feature));const plotFeatures=[...preferred,...chosen.filter(feature=>!preferred.includes(feature))].slice(0,4);while(plotFeatures.length<4&&features[plotFeatures.length])plotFeatures.push(features[plotFeatures.length]);
 const plots=plotFeatures.map((feature,index)=>{const raw=rows.map(r=>r[feature]).filter(Number.isFinite);const transformed=scale(raw,method);const partner=rows.map(r=>r[features[(features.indexOf(feature)+1)%features.length]]).filter(Number.isFinite).slice(0,raw.length);const densityPair=pairedBins(logScale?raw.map(v=>Math.log1p(Math.max(0,v))):raw,transformed);const scatterPair=pairedScatter(raw,partner,method);return{feature,label:uploaded?feature:DISPLAY_LABELS[index]??feature,raw,transformed,rawBins:densityPair.raw,scaledBins:densityPair.scaled,rawScatter:scatterPair.raw,scaledScatter:scatterPair.scaled,before:{mean:mean(raw),std:std(raw)},after:{mean:mean(transformed),std:std(transformed)}}});
 const upload=async(file?:File)=>{if(!file)return;const lines=(await file.text()).trim().split(/\r?\n/);const headers=lines[0].split(',').map(s=>s.trim());const parsed=lines.slice(1).map(line=>line.split(',').map(Number)).filter(values=>values.length===headers.length&&values.every(Number.isFinite));if(parsed.length<8){setStatus('CSV needs at least 8 complete numeric rows');return}const nextRows=parsed.map(values=>Object.fromEntries(headers.map((h,i)=>[h,values[i]])));setUploaded({name:file.name,rows:nextRows,features:headers});setSelected(headers);setStatus(`${file.name} · ${nextRows.length} rows loaded`)};
 const chooseDataset=(value:DatasetKey)=>{setDataset(value);setUploaded(null);setSelected(DATASETS[value].features);setStatus(`${value} loaded`)};const reset=()=>{setDataset('Wine Quality (White)');setUploaded(null);setMethod('zscore');setCustom(false);setSelected(DATASETS['Wine Quality (White)'].features);setSearch('');setDensity(true);setScatter(true);setLinkAxes(true);setLogScale(false);setStatus('Scaling view reset')};
 return <div className={`sc-page ${collapsed?'collapsed':''}`}>
  <aside className="sc-side"><a href="/" className="sc-brand"><span>◇</span><b>Mega ML<small>AI Observatory</small></b></a><button className="sc-close" onClick={()=>setCollapsed(v=>!v)}>×</button><button className="home" onClick={()=>go('Home')}>⌂　Home</button><nav><small>LEARN</small>{['♙　Explore','⌘　Pathways','▧　Notebook'].map(x=><button key={x} onClick={()=>go(x)}>{x}<i>›</i></button>)}<hr/><small>TOPICS</small>{['1. Supervised Learning','2. Unsupervised Learning','3. Deep Learning','4. Feature Engineering'].map(x=><button key={x} onClick={()=>go(x)}>{x}<i>›</i></button>)}<button className="active">　Scaling & Normalization　●</button>{['　Encoding Categorical','　Feature Selection','　Feature Interactions','5. Model Evaluation','6. MLOps'].map(x=><button key={x} onClick={()=>go(x)}>{x}<i>›</i></button>)}</nav><section className="level"><b>◉　Level 12</b><progress max="3600" value="2450"/><small>2,450 / 3,600 XP</small><p>Daily Streak <b>🔥 7</b></p><button onClick={()=>setStatus('Leaderboard opened')}>♧　Leaderboard</button></section></aside>
  <header className="sc-head"><div><h1>Scaling & Normalization</h1><p>Make features comparable. Improve model performance and stability.</p></div><section><span>Lesson Progress <b>68%</b></span><progress max="100" value="68"/><button onClick={()=>setStatus('Continued to method comparison')}>Continue</button><button onClick={()=>setStatus('Lesson menu opened')}>⌄</button></section><nav>{TABS.map((tab,i)=><button className={activeTab===tab?'active':''} onClick={()=>{setActiveTab(tab);setStatus(`${tab} view selected`)}} key={tab}><i>{['♧','⊕','▦','✣','◉','〽','⌘','ⓘ'][i]}</i>{tab}</button>)}</nav><div className={`dataset-bar${labHide(activeTab, "Dataset")}`}><label><small>Sample Dataset</small><select aria-label="Sample Dataset" value={dataset} onChange={e=>chooseDataset(e.target.value as DatasetKey)}>{Object.keys(DATASETS).map(x=><option key={x}>{x}</option>)}</select></label><span>Samples<b>{uploaded?.rows.length.toLocaleString()??DATASETS[dataset].rows.toLocaleString()}</b></span><span>Features<b>{features.length}</b></span><button onClick={()=>setStatus('Dataset details opened')}>▣　Dataset</button><button onClick={()=>fileRef.current?.click()}>⇧　Upload</button><input ref={fileRef} type="file" hidden accept=".csv,text/csv" onChange={e=>void upload(e.target.files?.[0])}/></div></header>
  <main className="sc-main"><LabLessonOrWork tab={activeTab} route="/ml/preprocessing/scaling-normalization"><section className={`view-bar${labHide(activeTab, "Visualize", "Train")}`}><span>View</span><button className="active">Distributions</button><button onClick={()=>setStatus('Scatter geometry focused')}>Scatter (Geometry)</button><i/><span>● Raw (Original)</span><span className="green">● Scaled (Transformed)</span></section><section className={`plot-grid${labHide(activeTab, "Visualize", "Train")}`}>{plots.map((p,index)=><article key={`${p.feature}-${index}`}><h2>{index+1}. {p.label}　ⓘ</h2><div className="density"><button onClick={()=>setStatus(`${p.feature} expanded`)}>↗</button>{density&&<svg viewBox="0 0 208 83" role="img" aria-label={`${p.feature} distribution`}><path className="raw-area" d={`${path(p.rawBins)} L196,74 L12,74 Z`}/><path className="scaled-area" d={`${path(p.scaledBins)} L196,74 L12,74 Z`}/><path className="raw-line" d={path(p.rawBins)}/><path className="scaled-line" d={path(p.scaledBins)}/></svg>}<small>{p.label}</small></div><div className="arrow">↓</div><div className="scatter">{scatter&&<svg viewBox="0 0 208 105" role="img" aria-label={`${p.feature} raw and scaled scatter`}><g className="grid">{[25,50,75].map(v=><line key={v} x1="8" x2="202" y1={v} y2={v}/>)}</g>{p.rawScatter.map((q,i)=><circle className="raw-dot" key={`r${i}`} cx={q.x} cy={q.y} r="1.4"/>)}{p.scaledScatter.map((q,i)=><circle className="scaled-dot" key={`s${i}`} cx={linkAxes?q.x+2:q.x} cy={q.y} r="1.3"/>)}</svg>}<p><span>● Raw</span><span className="green">● Scaled</span></p></div></article>)}</section><section className={`key-insights${labHide(activeTab, "Metrics")}`}><h2>⊕　Key Insights</h2><div><article><b>⚖　Scale Matters</b><p>Features are on very different scales. Example: values range widely across active columns.</p></article><article><b>◯　After Scaling</b><p>All features are transformed to be comparable, improving distance-based algorithms.</p></article><article><b>⌘　Geometry Preserved</b><p>Scaling preserves relationships within features but changes geometry across features.</p></article><article><b>◎　Outliers</b><p>Robust Scaling reduces the influence of outliers compared to Standardization and Min-Max.</p></article></div></section></LabLessonOrWork></main>
  <aside className={`sc-controls${labHide(activeTab, "Train", "Transform", "Visualize")}`}><section className="panel methods"><h2>Scaling Method</h2><button className={method==='zscore'?'active':''} onClick={()=>setMethod('zscore')}>Standardization (Z-Score)<i>●</i></button><button className={method==='minmax'?'active':''} onClick={()=>setMethod('minmax')}>Min-Max Scaling (0–1)</button><button className={method==='robust'?'active':''} onClick={()=>setMethod('robust')}>Robust Scaling (IQR)</button></section><section className="panel feature-control"><h2>Feature Selection</h2><div className="choice"><button className={!custom?'active':''} onClick={()=>setCustom(false)}>All Features ({features.length})</button><button className={custom?'active':''} onClick={()=>setCustom(true)}>Custom</button></div><input aria-label="Search features" placeholder="⌕  Search features..." value={search} onChange={e=>setSearch(e.target.value)}/><div className="feature-list">{visibleFeatures.map(f=><label key={f}><input type="checkbox" checked={selected.includes(f)} onChange={e=>setSelected(values=>e.target.checked?[...values,f]:values.filter(v=>v!==f))}/>{f}</label>)}</div><small>+ {Math.max(0,features.length-6)} more features</small><hr/><h2>Options</h2>{[['Show density',density,setDensity],['Show scatter',scatter,setScatter],['Link axes',linkAxes,setLinkAxes],['Log scale (when possible)',logScale,setLogScale]].map(([label,value,setter])=><label className="toggle" key={String(label)}>{String(label)}<input type="checkbox" checked={Boolean(value)} onChange={e=>(setter as (value:boolean)=>void)(e.target.checked)}/><i/></label>)}<button className="reset" onClick={reset}>↻　Reset View</button><a href="?advanced=1">Open original scaling workbench →</a></section></aside>
  <footer className="sc-footer"><p><b>⬇　Why scale?</b> Scaling improves model performance, stability, and interpretability—especially for distance and gradient-based algorithms.</p><button onClick={()=>setStatus('Method comparison opened')}>Next up: Compare methods　→</button></footer><div className="sc-status">{status} · {plots[0]?.after.mean.toFixed(3)} mean / {plots[0]?.after.std.toFixed(3)} std</div>
 </div>
}
