import { aiVirtualLabs } from './catalog';

export type LearningCheck = { prompt: string; options: [string, string, string]; answer: number; explanation: string };
export type LearningContent = { goal: string; concepts: [string, string]; prerequisites: string[]; related: string[]; check: LearningCheck };

const content: Record<string, LearningContent> = {
  'uniform-cost-search': { goal: 'Find the least-cost route and explain why the next node is expanded.', concepts: ['path cost', 'priority queue'], prerequisites: [], related: ['a-star-search', 'greedy-best-first-search'], check: { prompt: 'Which frontier node does uniform-cost search expand next?', options: ['The shallowest node', 'The node with the smallest accumulated cost', 'The node closest to the goal on screen'], answer: 1, explanation: 'Uniform-cost search orders the frontier by cost from the start, g(n).' } },
  'iterative-deepening-depth-first-search': { goal: 'Trace repeated depth-limited passes and identify when the goal is found.', concepts: ['depth limit', 'search completeness'], prerequisites: ['ai-depth-first-search'], related: ['ai-depth-first-search', 'breadth-first-search'], check: { prompt: 'Why does iterative deepening restart the search?', options: ['To raise the depth limit', 'To randomize the graph', 'To lower all edge costs'], answer: 0, explanation: 'Each pass explores with a larger depth limit.' } },
  'a-star-search': { goal: 'Explain how path cost and heuristic combine to rank open nodes.', concepts: ['heuristic', 'f = g + h'], prerequisites: ['uniform-cost-search'], related: ['uniform-cost-search', 'greedy-best-first-search'], check: { prompt: 'What priority does A* assign to a node?', options: ['h only', 'g only', 'g + h'], answer: 2, explanation: 'A* ranks open nodes by f(n) = g(n) + h(n).' } },
  'simplified-memory-bounded-a-star-search': { goal: 'Observe what happens when the search frontier exceeds a memory bound.', concepts: ['memory bound', 'backed-up cost'], prerequisites: ['a-star-search'], related: ['a-star-search', 'beam-search'], check: { prompt: 'When memory fills, SMA* mainly keeps information about what?', options: ['Forgotten branch costs', 'Only visited coordinates', 'A random path'], answer: 0, explanation: 'Backed-up costs let a forgotten branch be reconsidered.' } },
  'hill-climbing-search': { goal: 'Identify local optima and explain why a greedy uphill move can stall.', concepts: ['local optimum', 'neighbor evaluation'], prerequisites: [], related: ['simulated-annealing', 'local-beam-search'], check: { prompt: 'Why might hill climbing stop before the global best?', options: ['No neighbor improves the current state', 'The search uses a queue', 'Rewards are discounted'], answer: 0, explanation: 'At a local optimum, available neighbors do not improve the evaluation.' } },
  'local-beam-search': { goal: 'Track how the best k candidates survive each iteration.', concepts: ['beam width', 'candidate selection'], prerequisites: ['hill-climbing-search'], related: ['beam-search', 'hill-climbing-search'], check: { prompt: 'What does beam width k control?', options: ['Number of retained candidates', 'Maximum edge cost', 'Reward discount'], answer: 0, explanation: 'The beam keeps the k best candidates at a search level.' } },
  'policy-iteration': { goal: 'Alternate policy evaluation and improvement until choices stabilize.', concepts: ['policy evaluation', 'policy improvement'], prerequisites: ['markov-decision-process-explorer'], related: ['value-iteration', 'markov-decision-process-explorer'], check: { prompt: 'What follows policy evaluation?', options: ['Policy improvement', 'Graph pruning', 'A new observation model'], answer: 0, explanation: 'Evaluation estimates the current policy, then improvement updates actions.' } },
  'value-iteration': { goal: 'Use Bellman updates to see values and a greedy policy converge.', concepts: ['Bellman update', 'value function'], prerequisites: ['markov-decision-process-explorer'], related: ['policy-iteration', 'q-learning'], check: { prompt: 'Value iteration repeatedly updates what?', options: ['Only the start cell', 'State values using best next actions', 'Hidden observations'], answer: 1, explanation: 'It applies Bellman optimality updates to state values.' } },
  'q-learning': { goal: 'Predict an action, calculate one TD update, and learn a route to the goal.', concepts: ['action selection', 'temporal difference'], prerequisites: ['markov-decision-process-explorer'], related: ['sarsa-learning', 'value-iteration', 'markov-decision-process-explorer'], check: { prompt: 'Which next-state value appears in Q-learning’s target?', options: ['The actual next action’s Q value', 'The maximum next-state Q value', 'The average reward so far'], answer: 1, explanation: 'Q-learning uses the maximum next-state Q value, even if the behavior explored.' } },
  'ai-depth-first-search': { goal: 'Trace stack expansion and backtracking through a graph.', concepts: ['stack', 'backtracking'], prerequisites: [], related: ['breadth-first-search', 'iterative-deepening-depth-first-search'], check: { prompt: 'Which data structure naturally drives depth-first search?', options: ['Stack', 'Priority queue', 'Probability table'], answer: 0, explanation: 'DFS follows the most recently discovered branch using a stack.' } },
  'greedy-best-first-search': { goal: 'Predict expansions based only on estimated distance to the goal.', concepts: ['heuristic', 'greedy frontier'], prerequisites: [], related: ['a-star-search', 'uniform-cost-search'], check: { prompt: 'What does greedy best-first search use to rank nodes?', options: ['g only', 'h only', 'g + h'], answer: 1, explanation: 'Greedy best-first search ranks nodes by its heuristic h(n).' } },
  'minimax-search': { goal: 'Back up leaf utilities through alternating maximizing and minimizing turns.', concepts: ['game tree', 'backed-up value'], prerequisites: [], related: ['alpha-beta-pruning', 'monte-carlo-tree-search'], check: { prompt: 'At a minimizing node, which child value is selected?', options: ['Largest', 'Smallest', 'Newest'], answer: 1, explanation: 'The minimizing player chooses the smallest available utility.' } },
  'bayesian-network-construction': { goal: 'Connect variables and conditional tables into a valid directed model.', concepts: ['conditional independence', 'DAG'], prerequisites: [], related: ['bayesian-network-inference'], check: { prompt: 'What structure must a Bayesian network graph have?', options: ['Directed and acyclic', 'Undirected and complete', 'A single chain'], answer: 0, explanation: 'A Bayesian network is a directed acyclic graph.' } },
  'bayesian-network-inference': { goal: 'Use evidence to update the probability of a query variable.', concepts: ['evidence', 'posterior'], prerequisites: ['bayesian-network-construction'], related: ['bayesian-network-construction', 'hidden-markov-model-forward-viterbi'], check: { prompt: 'What is a posterior probability?', options: ['A probability after considering evidence', 'The number of graph edges', 'A node’s initial label'], answer: 0, explanation: 'A posterior conditions the query on observed evidence.' } },
  'breadth-first-search': { goal: 'Follow queue order and verify level-by-level expansion.', concepts: ['queue', 'search depth'], prerequisites: [], related: ['ai-depth-first-search', 'bidirectional-search'], check: { prompt: 'Which nodes does breadth-first search visit first?', options: ['Deepest nodes', 'Lowest-cost nodes', 'Shallower nodes'], answer: 2, explanation: 'BFS expands a level before moving to the next depth.' } },
  'bidirectional-search': { goal: 'Trace two frontiers until they meet and reconstruct a route.', concepts: ['two frontiers', 'meeting point'], prerequisites: ['breadth-first-search'], related: ['breadth-first-search', 'uniform-cost-search'], check: { prompt: 'Where is the final path joined?', options: ['At the meeting state', 'At the first expanded state', 'At the highest heuristic'], answer: 0, explanation: 'The forward and backward parent chains join at their meeting state.' } },
  'beam-search': { goal: 'Explain how retaining only k states trades memory for completeness.', concepts: ['beam width', 'pruning'], prerequisites: ['breadth-first-search'], related: ['local-beam-search', 'simplified-memory-bounded-a-star-search'], check: { prompt: 'What can happen when a beam drops a candidate?', options: ['The best route may be lost', 'All paths become optimal', 'The goal moves'], answer: 0, explanation: 'Pruning to a fixed beam can discard the route to the best solution.' } },
  'simulated-annealing': { goal: 'Observe how temperature changes acceptance of worse moves.', concepts: ['temperature', 'probabilistic escape'], prerequisites: ['hill-climbing-search'], related: ['hill-climbing-search', 'genetic-algorithm'], check: { prompt: 'At higher temperature, worse moves are generally…', options: ['More likely to be accepted', 'Always forbidden', 'Converted into rewards'], answer: 0, explanation: 'Higher temperature supports exploration away from local optima.' } },
  'genetic-algorithm': { goal: 'Track selection, crossover, and mutation across generations.', concepts: ['selection', 'mutation'], prerequisites: [], related: ['simulated-annealing', 'local-beam-search'], check: { prompt: 'What does mutation add to a population?', options: ['New variation', 'A guaranteed optimum', 'A smaller state space'], answer: 0, explanation: 'Mutation introduces variation that selection can explore.' } },
  'monte-carlo-tree-search': { goal: 'Read rollout outcomes and visit counts when choosing a game move.', concepts: ['rollout', 'visit count'], prerequisites: ['minimax-search'], related: ['minimax-search', 'alpha-beta-pruning'], check: { prompt: 'What is a rollout in MCTS?', options: ['A simulated continuation of play', 'A fixed heuristic table', 'A graph edge deletion'], answer: 0, explanation: 'Rollouts sample continuations to estimate action value.' } },
  'alpha-beta-pruning': { goal: 'Identify branches whose values cannot affect the minimax choice.', concepts: ['alpha bound', 'beta bound'], prerequisites: ['minimax-search'], related: ['minimax-search', 'monte-carlo-tree-search'], check: { prompt: 'When can alpha-beta pruning skip a branch?', options: ['When its bound cannot change the choice', 'When its depth is even', 'When it contains a reward'], answer: 0, explanation: 'Bounds prove some branches cannot affect the minimax result.' } },
  'markov-decision-process-explorer': { goal: 'Connect states, actions, transitions, and rewards in an MDP.', concepts: ['transition', 'reward'], prerequisites: [], related: ['value-iteration', 'policy-iteration', 'q-learning'], check: { prompt: 'What does a transition model describe?', options: ['Possible next states and probabilities', 'Only the final score', 'The font used in the grid'], answer: 0, explanation: 'The model gives possible next states for a state-action pair.' } },
  'sarsa-learning': { goal: 'Contrast an on-policy SARSA update with Q-learning’s max target.', concepts: ['on-policy learning', 'temporal difference'], prerequisites: ['q-learning'], related: ['q-learning', 'markov-decision-process-explorer'], check: { prompt: 'Which next value enters the SARSA target?', options: ['The value of the actual next action', 'The maximum next-state value', 'The previous state reward'], answer: 0, explanation: 'SARSA uses the Q value of the next action actually selected.' } },
  'hidden-markov-model-forward-viterbi': { goal: 'Distinguish sequence likelihood from the most likely hidden path.', concepts: ['hidden state', 'observation likelihood'], prerequisites: ['bayesian-network-inference'], related: ['bayesian-network-inference', 'markov-decision-process-explorer'], check: { prompt: 'What does the Viterbi algorithm return?', options: ['Most likely hidden-state path', 'A maximum-reward action policy', 'Shortest weighted graph path'], answer: 0, explanation: 'Viterbi finds the most likely hidden-state sequence for the observations.' } },
};

export function learningContent(slug: string): LearningContent {
  const item = content[slug];
  if (!item) throw new Error(`Missing learning content for ${slug}`);
  return item;
}

export const learningSlugs = aiVirtualLabs.map((lab) => lab.slug);
