import { useMemo, useState } from 'react';
import { MessageSquare } from 'lucide-react';
import { PageHeader } from '../../../components/common/PageHeader';
import { Card, InfoBox } from '../../../components/common/Card';
import { sentimentDataset } from '../../../data/sampleDatasets';

const tokenize = (text: string) => text.toLowerCase().replace(/[^a-z0-9\s]/g, '').split(/\s+/).filter(Boolean);

export default function BagOfWordsPage() {
  const [docsText, setDocsText] = useState((sentimentDataset.data as { text: string }[]).slice(0, 5).map(row => row.text).join('\n'));
  const docs = docsText.split(/\n+/).filter(Boolean);
  const computed = useMemo(() => {
    const tokens = docs.map(tokenize);
    const vocabulary = [...new Set(tokens.flat())].sort();
    const matrix = tokens.map(row => vocabulary.map(term => row.filter(token => token === term).length));
    return { vocabulary, matrix, tokens };
  }, [docsText]);

  return (
    <div className="mx-auto max-w-7xl space-y-6 p-4">
      <PageHeader title="Bag of Words" subtitle="Real tokenization, vocabulary extraction, and document-term matrix in the browser." badge="Beginner" category="NLP" icon={<MessageSquare size={22} />} />
      <div className="grid grid-cols-1 gap-6 lg:grid-cols-[360px_1fr]">
        <Card title="Text Input">
          <textarea value={docsText} onChange={e => setDocsText(e.target.value)} rows={12} className="w-full rounded border border-gray-200 bg-white p-3 text-sm dark:border-gray-700 dark:bg-gray-900" />
        </Card>
        <div className="space-y-4">
          <Card title="Vocabulary Table">
            <div className="flex flex-wrap gap-2">{computed.vocabulary.map(term => <span key={term} className="rounded bg-blue-50 px-2 py-1 text-xs font-mono text-blue-700 dark:bg-blue-900/30 dark:text-blue-300">{term}</span>)}</div>
          </Card>
          <Card title="Document-Term Matrix">
            <div className="overflow-auto">
              <table className="w-full text-xs"><thead><tr><th className="p-2">doc</th>{computed.vocabulary.map(term => <th key={term} className="p-2 font-mono">{term}</th>)}</tr></thead><tbody>{computed.matrix.map((row, i) => <tr key={i}><th className="border border-gray-200 p-2 dark:border-gray-700">D{i + 1}</th>{row.map((value, j) => <td key={j} className="border border-gray-200 p-2 text-center font-mono dark:border-gray-700">{value}</td>)}</tr>)}</tbody></table>
            </div>
          </Card>
          <InfoBox type="info" title="Real Logic Cross-Check">Counts are generated by lowercasing, punctuation removal, whitespace tokenization, vocabulary union, then per-document term counts.</InfoBox>
        </div>
      </div>
    </div>
  );
}
